// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: attachments.sql

package db

import (
	"context"
	"database/sql"
)

const createAttachment = `-- name: CreateAttachment :exec

INSERT INTO attachments (id, workspace_id, doc_id, filename, mime, size_bytes, storage_key)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateAttachmentParams struct {
	ID          string         `json:"id"`
	WorkspaceID string         `json:"workspace_id"`
	DocID       sql.NullString `json:"doc_id"`
	Filename    string         `json:"filename"`
	Mime        string         `json:"mime"`
	SizeBytes   int64          `json:"size_bytes"`
	StorageKey  string         `json:"storage_key"`
}

// Copyright (C) 2026 Deijose <tech@deijose.dev>
// SPDX-License-Identifier: AGPL-3.0-only
// Adjuntos (seccion 10): metadatos en el indice, bytes en el backend
// de almacenamiento (local o S3-compatible).
func (q *Queries) CreateAttachment(ctx context.Context, arg CreateAttachmentParams) error {
	_, err := q.db.ExecContext(ctx, createAttachment,
		arg.ID,
		arg.WorkspaceID,
		arg.DocID,
		arg.Filename,
		arg.Mime,
		arg.SizeBytes,
		arg.StorageKey,
	)
	return err
}

const deleteAttachment = `-- name: DeleteAttachment :exec
DELETE FROM attachments WHERE id = ? AND workspace_id = ?
`

type DeleteAttachmentParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) DeleteAttachment(ctx context.Context, arg DeleteAttachmentParams) error {
	_, err := q.db.ExecContext(ctx, deleteAttachment, arg.ID, arg.WorkspaceID)
	return err
}

const getAttachment = `-- name: GetAttachment :one
SELECT id, workspace_id, doc_id, filename, mime, size_bytes, storage_key, created_at
FROM attachments
WHERE id = ? AND workspace_id = ?
`

type GetAttachmentParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) GetAttachment(ctx context.Context, arg GetAttachmentParams) (Attachment, error) {
	row := q.db.QueryRowContext(ctx, getAttachment, arg.ID, arg.WorkspaceID)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.DocID,
		&i.Filename,
		&i.Mime,
		&i.SizeBytes,
		&i.StorageKey,
		&i.CreatedAt,
	)
	return i, err
}

const listAttachmentsByWorkspace = `-- name: ListAttachmentsByWorkspace :many
SELECT id, workspace_id, doc_id, filename, mime, size_bytes, storage_key, created_at
FROM attachments
WHERE workspace_id = ?
ORDER BY created_at DESC
`

func (q *Queries) ListAttachmentsByWorkspace(ctx context.Context, workspaceID string) ([]Attachment, error) {
	rows, err := q.db.QueryContext(ctx, listAttachmentsByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Attachment{}
	for rows.Next() {
		var i Attachment
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.DocID,
			&i.Filename,
			&i.Mime,
			&i.SizeBytes,
			&i.StorageKey,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchAttachmentsByName = `-- name: SearchAttachmentsByName :many
SELECT id, workspace_id, doc_id, filename, mime, size_bytes, storage_key, created_at
FROM attachments
WHERE workspace_id = ?1 AND filename LIKE '%' || ?2 || '%'
ORDER BY created_at DESC
LIMIT ?3
`

type SearchAttachmentsByNameParams struct {
	WorkspaceID string         `json:"workspace_id"`
	Term        sql.NullString `json:"term"`
	MaxResults  int64          `json:"max_results"`
}

func (q *Queries) SearchAttachmentsByName(ctx context.Context, arg SearchAttachmentsByNameParams) ([]Attachment, error) {
	rows, err := q.db.QueryContext(ctx, searchAttachmentsByName, arg.WorkspaceID, arg.Term, arg.MaxResults)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Attachment{}
	for rows.Next() {
		var i Attachment
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.DocID,
			&i.Filename,
			&i.Mime,
			&i.SizeBytes,
			&i.StorageKey,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
