// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	AddMembership(ctx context.Context, arg AddMembershipParams) error
	CountUsers(ctx context.Context) (int64, error)
	// Copyright (C) 2026 Deijose <tech@deijose.dev>
	// SPDX-License-Identifier: AGPL-3.0-only
	// Adjuntos (seccion 10): metadatos en el indice, bytes en el backend
	// de almacenamiento (local o S3-compatible).
	CreateAttachment(ctx context.Context, arg CreateAttachmentParams) error
	// Copyright (C) 2026 Deijose <tech@deijose.dev>
	// SPDX-License-Identifier: AGPL-3.0-only
	CreateDoc(ctx context.Context, arg CreateDocParams) error
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error
	// Copyright (C) 2026 Deijose <tech@deijose.dev>
	// SPDX-License-Identifier: AGPL-3.0-only
	// Saved views: filtros serializados por workspace (D1).
	CreateSavedView(ctx context.Context, arg CreateSavedViewParams) error
	// Copyright (C) 2026 Deijose <tech@deijose.dev>
	// SPDX-License-Identifier: AGPL-3.0-only
	CreateUser(ctx context.Context, arg CreateUserParams) error
	// Copyright (C) 2026 Deijose <tech@deijose.dev>
	// SPDX-License-Identifier: AGPL-3.0-only
	CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) error
	DeleteAttachment(ctx context.Context, arg DeleteAttachmentParams) error
	DeleteDocShare(ctx context.Context, docID string) error
	DeleteExpiredRefreshTokens(ctx context.Context) error
	DeleteMembershipsOfWorkspace(ctx context.Context, workspaceID string) error
	DeleteSavedView(ctx context.Context, arg DeleteSavedViewParams) error
	DeleteTasksForDoc(ctx context.Context, docID string) error
	DeleteWorkspaceAttachments(ctx context.Context, workspaceID string) error
	DeleteWorkspaceChanges(ctx context.Context, workspaceID string) error
	DeleteWorkspaceCommands(ctx context.Context, workspaceID string) error
	DeleteWorkspaceIndex(ctx context.Context, workspaceID string) error
	DeleteWorkspaceRows(ctx context.Context, id string) error
	DeleteWorkspaceTasks(ctx context.Context, workspaceID string) error
	GetAttachment(ctx context.Context, arg GetAttachmentParams) (Attachment, error)
	GetChangesAfter(ctx context.Context, arg GetChangesAfterParams) ([]ChangeLog, error)
	GetDoc(ctx context.Context, arg GetDocParams) (Doc, error)
	GetDocByID(ctx context.Context, arg GetDocByIDParams) (GetDocByIDRow, error)
	GetDocByPath(ctx context.Context, arg GetDocByPathParams) (GetDocByPathRow, error)
	GetDocShare(ctx context.Context, docID string) (DocShare, error)
	GetDocShareByToken(ctx context.Context, token string) (DocShare, error)
	GetDocVersionByID(ctx context.Context, id int64) (DocVersion, error)
	GetDocVersions(ctx context.Context, arg GetDocVersionsParams) ([]DocVersion, error)
	GetMembership(ctx context.Context, arg GetMembershipParams) (Membership, error)
	// Lookup publico: el token ES la capacidad (no hay workspace explicito).
	// Devuelve slug para leer el archivo canonico del store.
	GetPublicDocByToken(ctx context.Context, token string) (GetPublicDocByTokenRow, error)
	GetRefreshTokenByID(ctx context.Context, id string) (RefreshToken, error)
	GetSavedView(ctx context.Context, arg GetSavedViewParams) (SavedView, error)
	GetTaskByID(ctx context.Context, arg GetTaskByIDParams) (GetTaskByIDRow, error)
	GetTaskByUID(ctx context.Context, arg GetTaskByUIDParams) (Task, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id string) (User, error)
	// Copyright (C) 2026 Deijose <tech@deijose.dev>
	// SPDX-License-Identifier: AGPL-3.0-only
	GetWorkspaceByID(ctx context.Context, id string) (Workspace, error)
	// Copyright (C) 2026 Deijose <tech@deijose.dev>
	// SPDX-License-Identifier: AGPL-3.0-only
	// Sync delta (seccion 9): cursor monotono por workspace + push con
	// deduplicacion por idempotency-key.
	InsertChange(ctx context.Context, arg InsertChangeParams) (InsertChangeRow, error)
	InsertDocVersion(ctx context.Context, arg InsertDocVersionParams) error
	IsCommandProcessed(ctx context.Context, arg IsCommandProcessedParams) (int64, error)
	LastChangeSeq(ctx context.Context, workspaceID string) (int64, error)
	ListAttachmentsByWorkspace(ctx context.Context, workspaceID string) ([]Attachment, error)
	ListBacklinksForGraph(ctx context.Context, workspaceID string) ([]Backlink, error)
	ListBacklinksTo(ctx context.Context, arg ListBacklinksToParams) ([]ListBacklinksToRow, error)
	ListDocsByWorkspace(ctx context.Context, workspaceID string) ([]Doc, error)
	ListDocsForGraph(ctx context.Context, workspaceID string) ([]ListDocsForGraphRow, error)
	ListMembersByWorkspace(ctx context.Context, workspaceID string) ([]ListMembersByWorkspaceRow, error)
	ListSavedViews(ctx context.Context, workspaceID string) ([]SavedView, error)
	ListTasksByDateRange(ctx context.Context, arg ListTasksByDateRangeParams) ([]Task, error)
	ListTasksByProject(ctx context.Context, arg ListTasksByProjectParams) ([]Task, error)
	// Copyright (C) 2026 Deijose <tech@deijose.dev>
	// SPDX-License-Identifier: AGPL-3.0-only
	ListTasksByWorkspace(ctx context.Context, arg ListTasksByWorkspaceParams) ([]Task, error)
	ListTasksDueToday(ctx context.Context, arg ListTasksDueTodayParams) ([]Task, error)
	ListTasksMineToday(ctx context.Context, arg ListTasksMineTodayParams) ([]Task, error)
	ListTasksPage(ctx context.Context, arg ListTasksPageParams) ([]Task, error)
	ListUsers(ctx context.Context) ([]ListUsersRow, error)
	ListWorkspacesByUser(ctx context.Context, userID string) ([]ListWorkspacesByUserRow, error)
	MarkCommandProcessed(ctx context.Context, arg MarkCommandProcessedParams) error
	RemoveMembership(ctx context.Context, arg RemoveMembershipParams) error
	RevokeRefreshToken(ctx context.Context, id string) error
	SearchAttachmentsByName(ctx context.Context, arg SearchAttachmentsByNameParams) ([]Attachment, error)
	SearchTasksByTitle(ctx context.Context, arg SearchTasksByTitleParams) ([]Task, error)
	SetDocUpdatedAt(ctx context.Context, arg SetDocUpdatedAtParams) error
	SetTaskDone(ctx context.Context, arg SetTaskDoneParams) error
	SoftDeleteDoc(ctx context.Context, arg SoftDeleteDocParams) error
	UpdateDocContent(ctx context.Context, arg UpdateDocContentParams) error
	UpdateMembershipRole(ctx context.Context, arg UpdateMembershipRoleParams) error
	UpdateWorkspaceName(ctx context.Context, arg UpdateWorkspaceNameParams) error
	UpsertDoc(ctx context.Context, arg UpsertDocParams) (string, error)
	// Copyright (C) 2026 Deijose <tech@deijose.dev>
	// SPDX-License-Identifier: AGPL-3.0-only
	// shares.sql - share-links publicos de documentos (ASCII puro: sqlc)
	UpsertDocShare(ctx context.Context, arg UpsertDocShareParams) error
	UpsertTask(ctx context.Context, arg UpsertTaskParams) error
}

var _ Querier = (*Queries)(nil)
