// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: shares.sql

package db

import (
	"context"
)

const deleteDocShare = `-- name: DeleteDocShare :exec
DELETE FROM doc_shares WHERE doc_id = ?
`

func (q *Queries) DeleteDocShare(ctx context.Context, docID string) error {
	_, err := q.db.ExecContext(ctx, deleteDocShare, docID)
	return err
}

const getDocShare = `-- name: GetDocShare :one
SELECT doc_id, token, created_by, created_at
FROM doc_shares WHERE doc_id = ?
`

func (q *Queries) GetDocShare(ctx context.Context, docID string) (DocShare, error) {
	row := q.db.QueryRowContext(ctx, getDocShare, docID)
	var i DocShare
	err := row.Scan(
		&i.DocID,
		&i.Token,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getDocShareByToken = `-- name: GetDocShareByToken :one
SELECT doc_id, token, created_by, created_at
FROM doc_shares WHERE token = ?
`

func (q *Queries) GetDocShareByToken(ctx context.Context, token string) (DocShare, error) {
	row := q.db.QueryRowContext(ctx, getDocShareByToken, token)
	var i DocShare
	err := row.Scan(
		&i.DocID,
		&i.Token,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getPublicDocByToken = `-- name: GetPublicDocByToken :one
SELECT d.id, d.workspace_id, w.slug, d.path, d.title, d.updated_at
FROM doc_shares s
JOIN docs d ON d.id = s.doc_id
JOIN workspaces w ON w.id = d.workspace_id
WHERE s.token = ? AND d.deleted_at IS NULL
`

type GetPublicDocByTokenRow struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
	Slug        string `json:"slug"`
	Path        string `json:"path"`
	Title       string `json:"title"`
	UpdatedAt   string `json:"updated_at"`
}

// Lookup publico: el token ES la capacidad (no hay workspace explicito).
// Devuelve slug para leer el archivo canonico del store.
func (q *Queries) GetPublicDocByToken(ctx context.Context, token string) (GetPublicDocByTokenRow, error) {
	row := q.db.QueryRowContext(ctx, getPublicDocByToken, token)
	var i GetPublicDocByTokenRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Slug,
		&i.Path,
		&i.Title,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertDocShare = `-- name: UpsertDocShare :exec

INSERT INTO doc_shares (doc_id, token, created_by)
VALUES (?, ?, ?)
ON CONFLICT (doc_id) DO UPDATE SET token = excluded.token,
    created_by = excluded.created_by,
    created_at = datetime('now')
`

type UpsertDocShareParams struct {
	DocID     string `json:"doc_id"`
	Token     string `json:"token"`
	CreatedBy string `json:"created_by"`
}

// Copyright (C) 2026 Deijose <tech@deijose.dev>
// SPDX-License-Identifier: AGPL-3.0-only
// shares.sql - share-links publicos de documentos (ASCII puro: sqlc)
func (q *Queries) UpsertDocShare(ctx context.Context, arg UpsertDocShareParams) error {
	_, err := q.db.ExecContext(ctx, upsertDocShare, arg.DocID, arg.Token, arg.CreatedBy)
	return err
}
