// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: views.sql

package db

import (
	"context"
	"database/sql"
)

const createSavedView = `-- name: CreateSavedView :exec

INSERT INTO saved_views (id, workspace_id, name, filters, created_by)
VALUES (?, ?, ?, ?, ?)
`

type CreateSavedViewParams struct {
	ID          string         `json:"id"`
	WorkspaceID string         `json:"workspace_id"`
	Name        string         `json:"name"`
	Filters     string         `json:"filters"`
	CreatedBy   sql.NullString `json:"created_by"`
}

// Copyright (C) 2026 Deijose <tech@deijose.dev>
// SPDX-License-Identifier: AGPL-3.0-only
// Saved views: filtros serializados por workspace (D1).
func (q *Queries) CreateSavedView(ctx context.Context, arg CreateSavedViewParams) error {
	_, err := q.db.ExecContext(ctx, createSavedView,
		arg.ID,
		arg.WorkspaceID,
		arg.Name,
		arg.Filters,
		arg.CreatedBy,
	)
	return err
}

const deleteSavedView = `-- name: DeleteSavedView :exec
DELETE FROM saved_views WHERE id = ? AND workspace_id = ?
`

type DeleteSavedViewParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) DeleteSavedView(ctx context.Context, arg DeleteSavedViewParams) error {
	_, err := q.db.ExecContext(ctx, deleteSavedView, arg.ID, arg.WorkspaceID)
	return err
}

const getSavedView = `-- name: GetSavedView :one
SELECT id, workspace_id, name, filters, created_by, created_at
FROM saved_views
WHERE id = ? AND workspace_id = ?
`

type GetSavedViewParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) GetSavedView(ctx context.Context, arg GetSavedViewParams) (SavedView, error) {
	row := q.db.QueryRowContext(ctx, getSavedView, arg.ID, arg.WorkspaceID)
	var i SavedView
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Filters,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listSavedViews = `-- name: ListSavedViews :many
SELECT id, workspace_id, name, filters, created_by, created_at
FROM saved_views
WHERE workspace_id = ?
ORDER BY name
`

func (q *Queries) ListSavedViews(ctx context.Context, workspaceID string) ([]SavedView, error) {
	rows, err := q.db.QueryContext(ctx, listSavedViews, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SavedView{}
	for rows.Next() {
		var i SavedView
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Filters,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
